### PR TITLE
Sometimes crash fix

### PR DESCRIPTION
**Pull request by JosefKuchar**
It sometimes crash on this time, so this is fix

### CODE REVIEW

**Comment by yackx** [comment]
Hello. Thank you for the PR. Could you please give me more info about "it crashed"? What happens exactly? The `except` block without any type is pretty large. I'd rather see it limited to a specific exception.

Also, there is already a `except urllib2.HTTPError, err` in `download.py`. Probably better to let the caller deal with the exception and print / exit / retry.

**Comment by JosefKuchar** [comment]
It was general error in soundcloud library

**Comment by yackx** [comment]
What exception precisely?

**Comment by JosefKuchar** [comment]
The bad think is that my friend deleted the playlist with the error :(

**Pull request closed without merging**
